export const tableHeaders = [
  "Equipment No.",
  "Asset Code",
  "System Status",
  "Functional Location",
  "Partner ID",
  "CCS Superior Equipment No.",
  "CCS Superior Equipment Technical ID No.",
  "Technical ID No.",
  "Authorization Group",
  "Planner Group",
  "Main Work Centre",
  "Division",
  "Start-up Date",
  "Manufacturer",
  "Manufacturer Country or Region",
  "Model No.",
  "Manufacturer Serial No.",
  "Acquisition Value",
  "Currency",
  "Acquisition Date",
  "Inventory No.",
  "Room/Floor",
  "Asset Tag No.",
  "Zone Tag No.",
  "User Status",
  "Customer Warranty Start",
  "Customer Warranty End",
  "Vendor Warranty Start",
  "Vendor Warranty End",
  "Equipment Long Text",
  "Equipment Description",
  "Make",
  "Quantity",
  "Equipment Location",
  "Motor",
  "Cooling Capacity (kW)",
];

export const columnSettings = [
  { data: "equipmentNo" },
  { data: "assetCode" },
  { data: "systemStatus" },
  { data: "functionalLocation" },
  { data: "partnerID" },
  { data: "cCSSuperiorEquipmentNo" },
  { data: "cCSSuperiorEquipmentTechnicalIDNo" },
  { data: "technicalIDNo" },
  { data: "authorizationGroup" },
  { data: "plannerGroup" },
  { data: "mainWorkCentre" },
  { data: "division" },
  { data: "startUpDate" },
  { data: "manufacturer" },
  { data: "manufacturerCountryOrRegion" },
  { data: "modelNo" },
  { data: "manufacturerSerialNo" },
  { data: "acquisitionValue" },
  { data: "currency" },
  { data: "acquisitionDate" },
  { data: "inventoryNo" },
  { data: "roomOrFloor" },
  { data: "assetTagNo" },
  { data: "zoneTagNo" },
  { data: "userStatus" },
  { data: "customerWarrantyStart" },
  { data: "customerWarrantyEnd" },
  { data: "vendorWarrantyStart" },
  { data: "vendorWarrantyEnd" },
  { data: "equipmentLongText" },
  { data: "equipmentDescription" },
  { data: "make" },
  { data: "quantity", type: "numeric" },
  { data: "equipmentLocation" },
  {
    data: "motor",
    type: "dropdown",
    source: ["AC MOTOR", "DC MOTOR"],
    strict: true,
    allowInvalid: false,
    renderer: "antdSelectRenderer",
    destroyRenderer: "destroyAntdSelectRenderer",
  },
  { data: "coolingCapacitykW" },
];

export const colWidths = [
  120, 280, 140, 150, 100, 210, 290, 130, 150, 110, 140, 80, 110, 110, 230, 90,
  170, 130, 80, 130, 110, 90, 110, 110, 100, 180, 170, 160, 160, 170, 170, 60,
  80, 150, 120, 170,
];
// export const tableData = [
//   {
//     equipmentNo: "11087083",
//     assetCode: "TP-TWNCC-NA-GF-HVAC-FCU-0003",
//     systemStatus: "Active",
//     functionalLocation: "TWNCC-AC",
//     partnerID: "220177:CIC [Construction Industry Council]",
//     cCSSuperiorEquipmentNo: "11087051",
//     cCSSuperiorEquipmentTechnicalIDNo: "",
//     technicalIDNo: "技術ID 12345",
//     authorizationGroup: "HV00:HSD1 & VESD",
//     plannerGroup: "AH0:ASSD & HSD1",
//     mainWorkCentre: "A4250:AS1-GF",
//     division: "08:BTSD",
//     startUpDate: "08.11.2010",
//     manufacturer: "索尼",
//     manufacturerCountryOrRegion: "JP:Japan",
//     modelNo: "型號123",
//     manufacturerSerialNo: "序號321",
//     acquisitionValue: 600,
//     currency: "HKD:Hong Kong Dollar",
//     acquisitionDate: "01.01.2010",
//     inventoryNo: "庫存 123",
//     roomOrFloor: "38樓20室",
//     assetTagNo: "資產編號 123",
//     zoneTagNo: "區域編號 123",
//     userStatus: "SER,LTS",
//     customerWarrantyStart: "05.09.2010",
//     customerWarrantyEnd: "04.09.2012",
//     vendorWarrantyStart: "03.08.2009",
//     vendorWarrantyEnd: "02.08.2013",
//     equipmentLongText: "設備備註1 設備備註2設備備註3 設備備註1105",
//     equipmentDescription: "TECHFREE",
//     make: "",
//     quantity: 234,
//     equipmentLocation: "設備位置",
//     motor: "AC MOTOR",
//     coolingCapacitykW: 200,
//   },

//   {
//     equipmentNo: "11087084",
//     assetCode: "TP-TWNCC-NA-GF-HVAC-FCU-0004",
//     systemStatus: "Active",
//     functionalLocation: "TWNCC-AC",
//     partnerID: "220177:CIC [Construction Industry Council]",
//     cCSSuperiorEquipmentNo: "11087051",
//     cCSSuperiorEquipmentTechnicalIDNo: "",
//     technicalIDNo: "",
//     authorizationGroup: "HV00:HSD1 & VESD",
//     plannerGroup: "AH0:ASSD & HSD1",
//     mainWorkCentre: "A4250:AS1-GF",
//     division: "08:BTSD",
//     startUpDate: "08.11.2010",
//     manufacturer: "索尼",
//     manufacturerCountryOrRegion: "JP:Japan",
//     modelNo: "型號123",
//     manufacturerSerialNo: "",
//     acquisitionValue: 600,
//     currency: "HKD:Hong Kong Dollar",
//     acquisitionDate: "01.01.2010",
//     inventoryNo: "庫存 123",
//     roomOrFloor: "38樓20室",
//     assetTagNo: "資產編號 123",
//     zoneTagNo: "區域編號 123",
//     userStatus: "SER,LTS",
//     customerWarrantyStart: "05.09.2010",
//     customerWarrantyEnd: "04.09.2012",
//     vendorWarrantyStart: "03.08.2009",
//     vendorWarrantyEnd: "02.08.2013",
//     equipmentLongText: "設備備註1 設備備註2 設備備註3",
//     equipmentDescription: "設備備註1105",
//     make: "TECHFREE",
//     quantity: 234,
//     equipmentLocation: "設備位置",
//     motor: "AC MOTOR",
//     coolingCapacitykW: 200,
//   },

//   {
//     equipmentNo: "11087085",
//     assetCode: "TP-TWNCC-NA-GF-HVAC-FCU-0003",
//     systemStatus: "Active",
//     functionalLocation: "TWNCC-AC",
//     partnerID: "220177:CIC [Construction Industry Council]",
//     cCSSuperiorEquipmentNo: "11087051",
//     cCSSuperiorEquipmentTechnicalIDNo: "",
//     technicalIDNo: "",
//     authorizationGroup: "HV00:HSD1 & VESD",
//     plannerGroup: "AH0:ASSD & HSD1",
//     mainWorkCentre: "A4250:AS1-GF",
//     division: "08:BTSD",
//     startUpDate: "08.11.2010",
//     manufacturer: "索尼",
//     manufacturerCountryOrRegion: "JP:Japan",
//     modelNo: "型號123",
//     manufacturerSerialNo: "",
//     acquisitionValue: 600,
//     currency: "HKD:Hong Kong Dollar",
//     acquisitionDate: "01.01.2010",
//     inventoryNo: "庫存 123",
//     roomOrFloor: "38樓20室",
//     assetTagNo: "資產編號 123",
//     zoneTagNo: "區域編號 123",
//     userStatus: "SER,LTS",
//     customerWarrantyStart: "05.09.2010",
//     customerWarrantyEnd: "04.09.2012",
//     vendorWarrantyStart: "03.08.2009",
//     vendorWarrantyEnd: "02.08.2013",
//     equipmentLongText: "設備備註1 設備備註2 設備備註3",
//     equipmentDescription: "設備備註1105",
//     make: "TECHFREE",
//     quantity: 234,
//     equipmentLocation: "設備位置",
//     motor: "AC MOTOR",
//     coolingCapacitykW: 200,
//   },

//   {
//     equipmentNo: "11087086",
//     assetCode: "TP-TWNCC-NA-GF-HVAC-FCU-0003",
//     systemStatus: "Mark Deleted",
//     functionalLocation: "TWNCC-AC",
//     partnerID: "100002:AMS [Auxiliary Medical Service]",
//     cCSSuperiorEquipmentNo: "11087051",
//     cCSSuperiorEquipmentTechnicalIDNo: "",
//     technicalIDNo: "20251021",
//     authorizationGroup: "HV00:HSD1 & VESD",
//     plannerGroup: "AH0:ASSD & HSD1",
//     mainWorkCentre: "A4250:AS1-GF",
//     division: "08:BTSD",
//     startUpDate: "08.11.2010",
//     manufacturer: "索尼",
//     manufacturerCountryOrRegion: "JP:Japan",
//     modelNo: "型號123",
//     manufacturerSerialNo: "20251021",
//     acquisitionValue: 600,
//     currency: "HKD:Hong Kong Dollar",
//     acquisitionDate: "01.01.2010",
//     inventoryNo: "庫存 123",
//     roomOrFloor: "38樓20室",
//     assetTagNo: "資產編號 123",
//     zoneTagNo: "區域編號 123",
//     userStatus: "SER,LTS",
//     customerWarrantyStart: "05.09.2010",
//     customerWarrantyEnd: "04.09.2012",
//     vendorWarrantyStart: "03.08.2009",
//     vendorWarrantyEnd: "02.08.2013",
//     equipmentLongText: "設備備註1\n設備備註2\n設備備註3",
//     equipmentDescription: "設備備註1105",
//     make: "TECHFREE",
//     quantity: 234,
//     equipmentLocation: "設備位置",
//     motor: "AC MOTOR",
//     coolingCapacitykW: 200,
//   },

//   {
//     equipmentNo: "11087088",
//     assetCode: "TP-TWNCC-NA-GF-HVAC-FCU-0003",
//     systemStatus: "Active",
//     functionalLocation: "TWNCC-AC",
//     partnerID: "200005:CAA [Council for Academic Accreditation]",
//     cCSSuperiorEquipmentNo: "11087051",
//     cCSSuperiorEquipmentTechnicalIDNo: "",
//     technicalIDNo: "",
//     authorizationGroup: "HV00:HSD1 & VESD",
//     plannerGroup: "AH0:ASSD & HSD1",
//     mainWorkCentre: "A4250:AS1-GF",
//     division: "08:BTSD",
//     startUpDate: "08.11.2010",
//     manufacturer: "索尼",
//     manufacturerCountryOrRegion: "JP:Japan",
//     modelNo: "型號123",
//     manufacturerSerialNo: "",
//     acquisitionValue: 600,
//     currency: "HKD:Hong Kong Dollar",
//     acquisitionDate: "01.01.2010",
//     inventoryNo: "庫存 123",
//     roomOrFloor: "38樓20室",
//     assetTagNo: "資產編號 123",
//     zoneTagNo: "區域編號 123",
//     userStatus: "SER",
//     customerWarrantyStart: "05.09.2010",
//     customerWarrantyEnd: "04.09.2012",
//     vendorWarrantyStart: "03.08.2009",
//     vendorWarrantyEnd: "02.08.2013",
//     equipmentLongText: "設備備註1\n設備備註2\n設備備註3",
//     equipmentDescription: "設備備註1105",
//     make: "TECHFREE",
//     quantity: 234,
//     equipmentLocation: "設備位置",
//     motor: "AC MOTOR",
//     coolingCapacitykW: 200,
//   },

//   {
//     equipmentNo: "11087089",
//     assetCode: "TP-TWNCC-NA-GF-HVAC-FCU-0006",
//     systemStatus: "Active",
//     functionalLocation: "TWNCC-AC",
//     partnerID: "100002:AMS [Auxiliary Medical Service]",
//     cCSSuperiorEquipmentNo: "11087051",
//     cCSSuperiorEquipmentTechnicalIDNo: "",
//     technicalIDNo: '1234!@#$%^&*()*+{}|:"<>?~',
//     authorizationGroup: "MN00:MUNSD",
//     plannerGroup: "H40:NDH (EMA)",
//     mainWorkCentre: "A4290:AS1-GFS",
//     division: "08:BTSD",
//     startUpDate: "25.12.2010",
//     manufacturer: '!@#%^&*()*+{}|:"<>?~',
//     manufacturerCountryOrRegion: "JP:Japan",
//     modelNo: 'Model1234!@#$%^&*()_+{}|:"<>?~',
//     manufacturerSerialNo: 'Serial123!@#$%^&*()*+{}|:"<>?~',
//     acquisitionValue: 98765432100.23,
//     currency: "HKD:Hong Kong Dollar",
//     acquisitionDate: "13.01.2010",
//     inventoryNo: 'Inve!@#$%^&*()*+{}|:"<>?~',
//     roomOrFloor: 'RoomFloot!@#$%^&*()_+{}|:"<>?~',
//     assetTagNo: '!@#%^&*()*+{}|:"<>?~',
//     zoneTagNo: '!@#%^&*()*+{}|:"<>?~',
//     userStatus: "SER,BOS,LTS",
//     customerWarrantyStart: "15.02.2010",
//     customerWarrantyEnd: "24.03.2011",
//     vendorWarrantyStart: "11.01.2010",
//     vendorWarrantyEnd: "24.05.2012",
//     equipmentLongText:
//       'This is AC1105 Equipment Long Text Description 1\nThis is AC1105 Equipment Long Text Description 2\nThis is AC1105 Equipment Long Text Description 3\nThis is AC1105 Equipment Long Text Description 4\nThis is AC1105 Equipment Long Text Description 5\nThis is AC1105 Equipment Long Text Description 6\nThis is AC1105 Equipment Long Text Description 7 \nThis is AC1105 Equipment Long Text Description 8\nThis is AC1105 Equipment Long Text Description 9 \nThis is AC1105 Equipment Long Text Description 10\nThis is AC1105 Equipment Long Text Description 11\nThis is AC1105 Equipment Long Text Description 12\nThis is AC1105 Equipment Long Text Description 13\nThis is AC1105 Equipment Long Text Description 14\nThis is AC1105 Equipment Long Text Description 15\nThis is AC1105 Equipment Long Text Description 16\nThis is AC1105 Equipment Long Text Description 17\nThis is AC1105 Equipment Long Text Description 18\nThis is AC1105 Equipment Long Text Description 19\n1234!@#$%^&*()_+{}|:""<>?~ Equipment Long t Description 20',
//     equipmentDescription: "!@#$%^&*()*+{}|",
//     make: "TECHFREE",
//     quantity: 999,
//     equipmentLocation: '1234EQUIP!@#$%^&*()*+{}|:"<>?~',
//     motor: "AC MOTOR",
//     coolingCapacitykW: 999,
//   },
// ];

export const tableData = Array.from({ length: 10000 }, (_, index) => {
  const baseIndex = index % 6; // Cycle through the 6 original templates
  const baseRow = [
    {
      equipmentNo: "11087083",
      assetCode: "TP-TWNCC-NA-GF-HVAC-FCU-0003",
      systemStatus: "Active",
      functionalLocation: "TWNCC-AC",
      partnerID: "220177:CIC [Construction Industry Council]",
      cCSSuperiorEquipmentNo: "11087051",
      cCSSuperiorEquipmentTechnicalIDNo: "",
      technicalIDNo: "技術ID 12345",
      authorizationGroup: "HV00:HSD1 & VESD",
      plannerGroup: "AH0:ASSD & HSD1",
      mainWorkCentre: "A4250:AS1-GF",
      division: "08:BTSD",
      startUpDate: "08.11.2010",
      manufacturer: "索尼",
      manufacturerCountryOrRegion: "JP:Japan",
      modelNo: "型號123",
      manufacturerSerialNo: "序號321",
      acquisitionValue: 600,
      currency: "HKD:Hong Kong Dollar",
      acquisitionDate: "01.01.2010",
      inventoryNo: "庫存 123",
      roomOrFloor: "38樓20室",
      assetTagNo: "資產編號 123",
      zoneTagNo: "區域編號 123",
      userStatus: "SER,LTS",
      customerWarrantyStart: "05.09.2010",
      customerWarrantyEnd: "04.09.2012",
      vendorWarrantyStart: "03.08.2009",
      vendorWarrantyEnd: "02.08.2013",
      equipmentLongText: "設備備註1 設備備註2設備備註3 設備備註1105",
      equipmentDescription: "TECHFREE",
      make: "",
      quantity: 234,
      equipmentLocation: "設備位置",
      motor: "AC MOTOR",
      coolingCapacitykW: 200,
    },
    {
      equipmentNo: "11087084",
      assetCode: "TP-TWNCC-NA-GF-HVAC-FCU-0004",
      systemStatus: "Active",
      functionalLocation: "TWNCC-AC",
      partnerID: "220177:CIC [Construction Industry Council]",
      cCSSuperiorEquipmentNo: "11087051",
      cCSSuperiorEquipmentTechnicalIDNo: "",
      technicalIDNo: "",
      authorizationGroup: "HV00:HSD1 & VESD",
      plannerGroup: "AH0:ASSD & HSD1",
      mainWorkCentre: "A4250:AS1-GF",
      division: "08:BTSD",
      startUpDate: "08.11.2010",
      manufacturer: "索尼",
      manufacturerCountryOrRegion: "JP:Japan",
      modelNo: "型號123",
      manufacturerSerialNo: "",
      acquisitionValue: 600,
      currency: "HKD:Hong Kong Dollar",
      acquisitionDate: "01.01.2010",
      inventoryNo: "庫存 123",
      roomOrFloor: "38樓20室",
      assetTagNo: "資產編號 123",
      zoneTagNo: "區域編號 123",
      userStatus: "SER,LTS",
      customerWarrantyStart: "05.09.2010",
      customerWarrantyEnd: "04.09.2012",
      vendorWarrantyStart: "03.08.2009",
      vendorWarrantyEnd: "02.08.2013",
      equipmentLongText: "設備備註1 設備備註2 設備備註3",
      equipmentDescription: "設備備註1105",
      make: "TECHFREE",
      quantity: 234,
      equipmentLocation: "設備位置",
      motor: "AC MOTOR",
      coolingCapacitykW: 200,
    },
    {
      equipmentNo: "11087085",
      assetCode: "TP-TWNCC-NA-GF-HVAC-FCU-0003",
      systemStatus: "Active",
      functionalLocation: "TWNCC-AC",
      partnerID: "220177:CIC [Construction Industry Council]",
      cCSSuperiorEquipmentNo: "11087051",
      cCSSuperiorEquipmentTechnicalIDNo: "",
      technicalIDNo: "",
      authorizationGroup: "HV00:HSD1 & VESD",
      plannerGroup: "AH0:ASSD & HSD1",
      mainWorkCentre: "A4250:AS1-GF",
      division: "08:BTSD",
      startUpDate: "08.11.2010",
      manufacturer: "索尼",
      manufacturerCountryOrRegion: "JP:Japan",
      modelNo: "型號123",
      manufacturerSerialNo: "",
      acquisitionValue: 600,
      currency: "HKD:Hong Kong Dollar",
      acquisitionDate: "01.01.2010",
      inventoryNo: "庫存 123",
      roomOrFloor: "38樓20室",
      assetTagNo: "資產編號 123",
      zoneTagNo: "區域編號 123",
      userStatus: "SER,LTS",
      customerWarrantyStart: "05.09.2010",
      customerWarrantyEnd: "04.09.2012",
      vendorWarrantyStart: "03.08.2009",
      vendorWarrantyEnd: "02.08.2013",
      equipmentLongText: "設備備註1 設備備註2 設備備註3",
      equipmentDescription: "設備備註1105",
      make: "TECHFREE",
      quantity: 234,
      equipmentLocation: "設備位置",
      motor: "AC MOTOR",
      coolingCapacitykW: 200,
    },
    {
      equipmentNo: "11087086",
      assetCode: "TP-TWNCC-NA-GF-HVAC-FCU-0003",
      systemStatus: "Mark Deleted",
      functionalLocation: "TWNCC-AC",
      partnerID: "100002:AMS [Auxiliary Medical Service]",
      cCSSuperiorEquipmentNo: "11087051",
      cCSSuperiorEquipmentTechnicalIDNo: "",
      technicalIDNo: "20251021",
      authorizationGroup: "HV00:HSD1 & VESD",
      plannerGroup: "AH0:ASSD & HSD1",
      mainWorkCentre: "A4250:AS1-GF",
      division: "08:BTSD",
      startUpDate: "08.11.2010",
      manufacturer: "索尼",
      manufacturerCountryOrRegion: "JP:Japan",
      modelNo: "型號123",
      manufacturerSerialNo: "20251021",
      acquisitionValue: 600,
      currency: "HKD:Hong Kong Dollar",
      acquisitionDate: "01.01.2010",
      inventoryNo: "庫存 123",
      roomOrFloor: "38樓20室",
      assetTagNo: "資產編號 123",
      zoneTagNo: "區域編號 123",
      userStatus: "SER,LTS",
      customerWarrantyStart: "05.09.2010",
      customerWarrantyEnd: "04.09.2012",
      vendorWarrantyStart: "03.08.2009",
      vendorWarrantyEnd: "02.08.2013",
      equipmentLongText: "設備備註1\n設備備註2\n設備備註3",
      equipmentDescription: "設備備註1105",
      make: "TECHFREE",
      quantity: 234,
      equipmentLocation: "設備位置",
      motor: "AC MOTOR",
      coolingCapacitykW: 200,
    },
    {
      equipmentNo: "11087088",
      assetCode: "TP-TWNCC-NA-GF-HVAC-FCU-0003",
      systemStatus: "Active",
      functionalLocation: "TWNCC-AC",
      partnerID: "200005:CAA [Council for Academic Accreditation]",
      cCSSuperiorEquipmentNo: "11087051",
      cCSSuperiorEquipmentTechnicalIDNo: "",
      technicalIDNo: "",
      authorizationGroup: "HV00:HSD1 & VESD",
      plannerGroup: "AH0:ASSD & HSD1",
      mainWorkCentre: "A4250:AS1-GF",
      division: "08:BTSD",
      startUpDate: "08.11.2010",
      manufacturer: "索尼",
      manufacturerCountryOrRegion: "JP:Japan",
      modelNo: "型號123",
      manufacturerSerialNo: "",
      acquisitionValue: 600,
      currency: "HKD:Hong Kong Dollar",
      acquisitionDate: "01.01.2010",
      inventoryNo: "庫存 123",
      roomOrFloor: "38樓20室",
      assetTagNo: "資產編號 123",
      zoneTagNo: "區域編號 123",
      userStatus: "SER",
      customerWarrantyStart: "05.09.2010",
      customerWarrantyEnd: "04.09.2012",
      vendorWarrantyStart: "03.08.2009",
      vendorWarrantyEnd: "02.08.2013",
      equipmentLongText: "設備備註1\n設備備註2\n設備備註3",
      equipmentDescription: "設備備註1105",
      make: "TECHFREE",
      quantity: 234,
      equipmentLocation: "設備位置",
      motor: "AC MOTOR",
      coolingCapacitykW: 200,
    },
    {
      equipmentNo: "11087089",
      assetCode: "TP-TWNCC-NA-GF-HVAC-FCU-0006",
      systemStatus: "Active",
      functionalLocation: "TWNCC-AC",
      partnerID: "100002:AMS [Auxiliary Medical Service]",
      cCSSuperiorEquipmentNo: "11087051",
      cCSSuperiorEquipmentTechnicalIDNo: "",
      technicalIDNo: '1234!@#$%^&*()*+{}|:"<>?~',
      authorizationGroup: "MN00:MUNSD",
      plannerGroup: "H40:NDH (EMA)",
      mainWorkCentre: "A4290:AS1-GFS",
      division: "08:BTSD",
      startUpDate: "25.12.2010",
      manufacturer: '!@#%^&*()*+{}|:"<>?~',
      manufacturerCountryOrRegion: "JP:Japan",
      modelNo: 'Model1234!@#$%^&*()_+{}|:"<>?~',
      manufacturerSerialNo: 'Serial123!@#$%^&*()*+{}|:"<>?~',
      acquisitionValue: 98765432100.23,
      currency: "HKD:Hong Kong Dollar",
      acquisitionDate: "13.01.2010",
      inventoryNo: 'Inve!@#$%^&*()*+{}|:"<>?~',
      roomOrFloor: 'RoomFloot!@#$%^&*()_+{}|:"<>?~',
      assetTagNo: '!@#%^&*()*+{}|:"<>?~',
      zoneTagNo: '!@#%^&*()*+{}|:"<>?~',
      userStatus: "SER,BOS,LTS",
      customerWarrantyStart: "15.02.2010",
      customerWarrantyEnd: "24.03.2011",
      vendorWarrantyStart: "11.01.2010",
      vendorWarrantyEnd: "24.05.2012",
      equipmentLongText:
        'This is AC1105 Equipment Long Text Description 1\nThis is AC1105 Equipment Long Text Description 2\nThis is AC1105 Equipment Long Text Description 3\nThis is AC1105 Equipment Long Text Description 4\nThis is AC1105 Equipment Long Text Description 5\nThis is AC1105 Equipment Long Text Description 6\nThis is AC1105 Equipment Long Text Description 7 \nThis is AC1105 Equipment Long Text Description 8\nThis is AC1105 Equipment Long Text Description 9 \nThis is AC1105 Equipment Long Text Description 10\nThis is AC1105 Equipment Long Text Description 11\nThis is AC1105 Equipment Long Text Description 12\nThis is AC1105 Equipment Long Text Description 13\nThis is AC1105 Equipment Long Text Description 14\nThis is AC1105 Equipment Long Text Description 15\nThis is AC1105 Equipment Long Text Description 16\nThis is AC1105 Equipment Long Text Description 17\nThis is AC1105 Equipment Long Text Description 18\nThis is AC1105 Equipment Long Text Description 19\n1234!@#$%^&*()_+{}|:""<>?~ Equipment Long t Description 20',
      equipmentDescription: "!@#$%^&*()*+{}|",
      make: "TECHFREE",
      quantity: 999,
      equipmentLocation: '1234EQUIP!@#$%^&*()*+{}|:"<>?~',
      motor: "AC MOTOR",
      coolingCapacitykW: 999,
    },
  ][baseIndex];

  // Create a deep copy of the base row with unique equipment number
  return {
    ...baseRow,
    equipmentNo: (parseInt(baseRow.equipmentNo) + index).toString(),
  };
});
